name: CodeClimateTests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Set up Code Climate's Test Reporter
      - name: Setup Code Climate Reporter
        uses: remarkablemark/setup-codeclimate@v2

      # Step 5: Run Tests and Upload Coverage to Code Climate
      - name: Run Tests and Upload Coverage
        run: |
          cc-test-reporter before-build
          npm test
          cc-test-reporter after-build --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
